server:
   port: 8090
   servlet:
      contextPath: /treinamento
      
spring:
   application:
      name: treinamento
      
   datasource:
      url: jdbc:mysql://localhost:3000/treinamento
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: '#B4c4glini'
      
   jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
      generate-ddl: false
      hibernate:
         ddl-auto: none
         
   security:
      oauth2:
         resourceserver:
            opaquetoken:
               client-id: treinamento-id
               client-secret: treinamento-secret